version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
#    labels:
#      - traefik.http.routers.inventory.rule=Host(`inventory.localhost`)
#      - traefik.http.services.inventory.loadbalancer.server.port=80
    volumes:
      - ./api:/var/www/backend
      - ./client:/var/www/client
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
      - internal
    depends_on:
      - client

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /var/www/client
    volumes:
      - ./client:/var/www/client
      - /var/www/client/node_modules
    depends_on:
      - backend
    networks:
      - internal

  backend:
    build:
      args:
        user: bdktech
        uid: 1000
      context: ./api
      dockerfile: Dockerfile
    working_dir: /var/www/backend
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./api:/var/www/backend
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mysql
#    ports:
#      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "W@ts0n#1"
      MYSQL_DATABASE: "inventory_tracker"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    networks:
      - internal

networks:
  web:
    external: true
  internal:
    external: false